### PR TITLE
Adds ZBX_NOTSUPPORTED

### PR DESCRIPTION
**Pull request by akomic**

### CODE REVIEW

**Comment by jbfavre** [comment]
Thanks for you contribution.

I've a question though. Where does the `state` filed come from ?
I can't find it in `zabbix sender` specification as found in https://www.zabbix.org/wiki/Docs/protocols/zabbix_sender/3.4

**Comment by akomic** [comment]
It's specified here
https://www.zabbix.com/documentation/3.2/manual/appendix/items/activepassive?s[]=zbx&s[]=notsupported

Tested, it works.

**Comment by akomic** [comment]
Is there a chance for this to be merged and new release made soon. I have another project depending on this and having to manually install from forked repo is a problem.

**Comment by jbfavre** [comment]
@akomic sorry for long silence, was very busy at work.
Did you run, and pass, tests ?

I yes, I shall merge it and release a new version this week-end

**Comment by akomic** [comment]
Yes

**Comment by akomic** [comment]
What's the holdup?

**Comment by jbfavre** [comment]
Sorry for the very long time.
Will release a new version today

**Pull request merged**
